name: .NET XUnit Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    strategy:
      matrix:
        configuration: [Debug, Release]
        # For a list of available runner types, refer to
        # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on
        os: [windows-latest, ubuntu-latest]

    runs-on: ${{ matrix.os }}

    env:
        # Path to the solution file relative to the root of the project.
        SOLUTION_FILE_PATH: RSAUtil.sln

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x

    - name: Restore NuGet packages
      run: nuget restore ${{env.SOLUTION_FILE_PATH}}

    # Execute all unit tests in the solution
    - name: Execute unit tests
      run: dotnet test

    # Build
    - name: Build
      run: dotnet build --configuration $env:Configuration $env:SOLUTION_FILE_PATH
      env:
        Configuration: ${{ matrix.configuration }}
